version: 2
jobs:
  build:
    docker:
      - image: docker:18.03.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build 
          command: |
            apk add --update python openssh git curl
            BRANCH=${CIRCLE_BRANCH#*/}
            source ./VERSION
            FROM_RP_TAG=v5.0.0
            if [[ ! -z $CIRCLE_TAG ]]; then
              VERSION_TAG="${VERSION}"
            elif [[ $BRANCH == develop ]]; then
              VERSION_TAG="${VERSION}-dev"
            else
              VERSION_TAG="ci-${VERSION}-${BRANCH}"
            fi
            docker login -u $DOCKER_USER -p $DOCKER_PASS

            # Build the container with default branding
            docker build --build-arg MAILROOM_VERSION=$MAILROOM_VERSION -t istresearch/mailroom:${VERSION_TAG} -f Dockerfile .
            docker push istresearch/mailroom:${VERSION_TAG}

            #if [[ $BRANCH == develop ]]; then
            docker tag istresearch/mailroom:${VERSION_TAG} istresearch/mailroom:ci-develop
            docker push istresearch/mailroom:ci-develop
            #fi

      - run:
          name: Deploy
          command: |
            BRANCH=${CIRCLE_BRANCH#*/}
            if [[ $BRANCH == develop ]] || [[ $BRANCH == master ]]; then
              curl -XPOST --header "Content-Type: application/json" -d '{"'"branch"'":"'"$TRIGGER_PROJECT_BRANCH"'"}' https://circleci.com/api/v1.1/project/github/$ORGANIZATION/$TRIGGER_PROJECT/build?circle-token=$CIRCLE_TOKEN
              printf "\n\nBuild triggered\n\n"
              printf "Follow the progress of the build on \nhttps://circleci.com/gh/$ORGANIZATION/$TRIGGER_PROJECT/tree/$TRIGGER_PROJECT_BRANCH"
            else
              echo "Skipping deploy step"
            fi
        
workflows:
  version: 2
  pipeline:
    jobs:
      - build:
          context: globalconfig
          filters:
            tags:
              ignore: /^test-.*/
